const data = [
    {
        namn: "Vesuvio",
        pris: "95:-",
        ingredienser: ["Kokt italiensk skinka"],
        kategori: "pizzor",
    },
    {
        namn: "Capricciosa",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka", "färska champinjoner"],
        kategori: "pizzor",
    },
    {
        namn: "Hawaii",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka", "ananas"],
        kategori: "pizzor",
    },
    {
        namn: "Calzone (inbakad)",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka"],
        kategori: "pizzor",
    },
    {
        namn: "Vegetariana",
        pris: "109:-",
        ingredienser: [
            "Färska champinjoner",
            "rödlök",
            "oliver",
            "kronärtskocka",
            "färska tomater",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Tomaso",
        pris: "114:-",
        ingredienser: ["Kokt italiensk skinka", "räkor"],
        kategori: "pizzor",
    },
    {
        namn: "Milano",
        pris: "104:-",
        ingredienser: ["Färska champinjoner", "rödlök", "Milano salami"],
        kategori: "pizzor",
    },
    {
        namn: "Napoli",
        pris: "114:-",
        ingredienser: ["Tonfisk", "rödlök", "räkor"],
        kategori: "pizzor",
    },
    {
        namn: "Marinara",
        pris: "109:-",
        ingredienser: ["Räkor", "kokta musslor"],
        kategori: "pizzor",
    },
    {
        namn: "Quattro stagioni",
        pris: "124:-",
        ingredienser: [
            "Kokt italiensk skinka",
            "färska champinjoner",
            "räkor",
            "kokta musslor",
            "kronärtskocka",
        ],
        kategori: "pizzor",
    },
    {
        namn: "All pollo",
        pris: "109:-",
        ingredienser: ["Kyckling", "Paprika", "rödlök", "marinerad vitlök"],
        kategori: "pizzor",
    },
    {
        namn: "Pollo tropicale",
        pris: "124:-",
        ingredienser: [
            "Kyckling",
            "ananas",
            "curry",
            "valnötter",
            "mangochutney",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Majorna special",
        pris: "114:-",
        ingredienser: [
            "Karl-Johan svamp",
            "oliver",
            "paprika",
            "kronärtskocka",
            "marinerad vitlök",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Kebabpizza",
        pris: "114:-",
        ingredienser: [
            "Kebabkött",
            "rödlök",
            "färska champinjoner",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Kebabpizza special",
        pris: "119:-",
        ingredienser: [
            "Kebabkött",
            "isbergssallad",
            "rödlök",
            "färska tomater",
            "gurka",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Falafelpizza",
        pris: "114:-",
        ingredienser: [
            "Falafel",
            "isbergssallad",
            "rödlök",
            "färska tomater",
            "gurka",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Ciao ciao",
        pris: "120:-",
        ingredienser: [
            "Oxfilé",
            "rödlök",
            "färska champinjoner",
            "bearnaisesås",
            "marinerad vitlök",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Husets special",
        pris: "114:-",
        ingredienser: ["Oxfilé", "färska champinjoner", "bearnaisesås"],
        kategori: "pizzor",
    },
    {
        namn: "Reale",
        pris: "120:-",
        ingredienser: ["Oxfilé", "rödlök", "salami från Milano", "gorgonzola"],
        kategori: "pizzor",
    },
    {
        namn: "Götas special",
        pris: "129:-",
        ingredienser: [
            "Kokt italiensk skinka",
            "färska champinjoner",
            "rödlök",
            "paprika",
            "Vitlök (marinerad)",
            "Oxfilé",
            "Bearnaisesås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Forte",
        pris: "114:-",
        ingredienser: [
            "Köttfärs",
            "paprika",
            "rödlök",
            "soltorkade tomater",
            "Piri-piri",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Acapulco",
        pris: "124:-",
        ingredienser: [
            "Oxfilé",
            "champinjoner",
            "rödlök",
            "marinerad vitlök",
            "färska tomater",
            "jalapeno",
        ],
        kategori: "pizzor",
    },

    {
        namn: "Insalata di pollo",
        pris: "119:-",
        ingredienser: ["Kycklingsallad"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di gamberi",
        pris: "119:-",
        ingredienser: ["Räksallad med handskalade räkor"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di kebab",
        pris: "119:-",
        ingredienser: ["Kebabsallad"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di formaggio",
        pris: "119:-",
        ingredienser: ["Sallad med blandade italienska ostar"],
        kategori: "salladOchKebaber",
    },

    {
        namn: "Bufalotta e basillico",
        pris: "125:-",
        ingredienser: [
            "Buffelmozzarella",
            "färska basilika",
            "italiensk olivolja",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Formaggiara",
        pris: "114:-",
        ingredienser: ["Tre olika italienska ostar"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Tonno e capperi",
        pris: "109:-",
        ingredienser: ["Tonfisk", "rödlök", "Kaprisbär"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Barbabietole con formagio di capra",
        pris: "115:-",
        ingredienser: [
            "Torkade rotfrukter",
            "getost",
            "italiensk honung",
            "valnötter",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Verde natura",
        pris: "120:-",
        ingredienser: [
            "Karl-Johan svamp",
            "soltorkade tomater",
            "paprika",
            "konärtskocka",
            "oliver",
            "kaprisbär",
            "zucchini",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Prosciutto crudo e pesto",
        pris: "109:-",
        ingredienser: ["Lufttorkad prasciutto", "pesto"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Parma noci",
        pris: "115:-",
        ingredienser: [
            "Lufttorkad prasciutto",
            "soltorkade tomater",
            "valnötter",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salsiccia con finocchio",
        pris: "115:-",
        ingredienser: [
            "Salsciccia smaksatt med fänkål",
            "Zucchini",
            "färska Champinjoner",
            "gorgonzolaost",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salame con tartufo",
        pris: "115:-",
        ingredienser: [
            "Salami från Modena",
            "inlagd paprika",
            "Provoloneost",
            "svart tryffelolja",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salame piccante",
        pris: "115:-",
        ingredienser: [
            "Salami från Milano",
            "rödlök",
            "soltorkade tomater",
            "piri-piri",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Carne macinata",
        pris: "120:-",
        ingredienser: [
            "Köttfärs",
            "oxfilé",
            "gorgonzolaost",
            "Karl-Johan svamp",
            "bearnaisesås",
            "vitlök",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Frutti di mare",
        pris: "120:-",
        ingredienser: [
            "Tonfisk",
            "kokta musslor",
            "handskalade räkor",
            "bläckfisk",
            "färsk vitlök",
        ],
        kategori: "lyxpizzor",
    },

    {
        namn: "Mariaplan special",
        pris: "119:-",
        ingredienser: ["kebabkött", "skinka", "pommes", "valfri sås"],
        kategori: "nyheter",
    },
    {
        namn: "Florens Pizza",
        pris: "104:-",
        ingredienser: ["spenat", "soltorkade tomater", "vitlökssås"],
        kategori: "nyheter",
    },
    {
        namn: "Kebabrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "kebabkött", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kebabtallrik",
        pris: "94:-",
        ingredienser: ["pommes", "Kebabkött", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kycklingtallrik",
        pris: "94:-",
        ingredienser: ["Kyckling", "Pommes", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kycklingrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "Kyckling", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Falafeltallrik",
        pris: "94:-",
        ingredienser: ["falafelbullar", "pommes", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Falafelrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "falafelbullar", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Pommestallrik",
        pris: "45:-",
        ingredienser: ["Krispiga och goda pommes frites"],
        kategori: "nyheter",
    },
    {
        namn: "Vegan kebabtallrik",
        pris: "109:-",
        ingredienser: ["vegankebab", "grönsaker", "vegansk sås"],
        kategori: "nyheter",
    },
    {
        namn: "Vegan kebabrulle",
        pris: "109:-",
        ingredienser: ["Vegankebab", "grönsaker", "vegansk sås"],
        kategori: "nyheter",
    },

    {
        namn: "Capricciosa Vegan",
        pris: "104:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "färska Champinjoner",
            "Vegan skinka",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Mexicana Vegan",
        pris: "114:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "rödlök",
            "Vegofärs",
            "Paprika",
            "Jalapeños",
            "ruccola",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Kebab Pizza",
        pris: "119:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "vegoKebab",
            "Isbergssallad",
            "färska tomater",
            "gurka",
            "rödlök",
            "peperoni",
            "vegansås",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Flygande Jakob Vegan",
        pris: "119:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "banan",
            "ananas",
            "valnötter",
            "vegoKyckling",
            "curry",
            "vegansås",
        ],
        kategori: "veganskaPizzor",
    },
]

const pizzorArr = [
    {
        namn: "Vesuvio",
        pris: "95:-",
        ingredienser: ["Kokt italiensk skinka"],
        kategori: "pizzor",
    },
    {
        namn: "Capricciosa",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka", "färska champinjoner"],
        kategori: "pizzor",
    },
    {
        namn: "Hawaii",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka", "ananas"],
        kategori: "pizzor",
    },
    {
        namn: "Calzone (inbakad)",
        pris: "99:-",
        ingredienser: ["Kokt italiensk skinka"],
        kategori: "pizzor",
    },
    {
        namn: "Vegetariana",
        pris: "109:-",
        ingredienser: [
            "Färska champinjoner",
            "rödlök",
            "oliver",
            "kronärtskocka",
            "färska tomater",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Tomaso",
        pris: "114:-",
        ingredienser: ["Kokt italiensk skinka", "räkor"],
        kategori: "pizzor",
    },
    {
        namn: "Milano",
        pris: "104:-",
        ingredienser: ["Färska champinjoner", "rödlök", "Milano salami"],
        kategori: "pizzor",
    },
    {
        namn: "Napoli",
        pris: "114:-",
        ingredienser: ["Tonfisk", "rödlök", "räkor"],
        kategori: "pizzor",
    },
    {
        namn: "Marinara",
        pris: "109:-",
        ingredienser: ["Räkor", "kokta musslor"],
        kategori: "pizzor",
    },
    {
        namn: "Quattro stagioni",
        pris: "124:-",
        ingredienser: [
            "Kokt italiensk skinka",
            "färska champinjoner",
            "räkor",
            "kokta musslor",
            "kronärtskocka",
        ],
        kategori: "pizzor",
    },
    {
        namn: "All pollo",
        pris: "109:-",
        ingredienser: ["Kyckling", "Paprika", "rödlök", "marinerad vitlök"],
        kategori: "pizzor",
    },
    {
        namn: "Pollo tropicale",
        pris: "124:-",
        ingredienser: [
            "Kyckling",
            "ananas",
            "curry",
            "valnötter",
            "mangochutney",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Majorna special",
        pris: "114:-",
        ingredienser: [
            "Karl-Johan svamp",
            "oliver",
            "paprika",
            "kronärtskocka",
            "marinerad vitlök",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Kebabpizza",
        pris: "114:-",
        ingredienser: [
            "Kebabkött",
            "rödlök",
            "färska champinjoner",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Kebabpizza special",
        pris: "119:-",
        ingredienser: [
            "Kebabkött",
            "isbergssallad",
            "rödlök",
            "färska tomater",
            "gurka",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Falafelpizza",
        pris: "114:-",
        ingredienser: [
            "Falafel",
            "isbergssallad",
            "rödlök",
            "färska tomater",
            "gurka",
            "Kebabsås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Ciao ciao",
        pris: "120:-",
        ingredienser: [
            "Oxfilé",
            "rödlök",
            "färska champinjoner",
            "bearnaisesås",
            "marinerad vitlök",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Husets special",
        pris: "114:-",
        ingredienser: ["Oxfilé", "färska champinjoner", "bearnaisesås"],
        kategori: "pizzor",
    },
    {
        namn: "Reale",
        pris: "120:-",
        ingredienser: ["Oxfilé", "rödlök", "salami från Milano", "gorgonzola"],
        kategori: "pizzor",
    },
    {
        namn: "Götas special",
        pris: "129:-",
        ingredienser: [
            "Kokt italiensk skinka",
            "färska champinjoner",
            "rödlök",
            "paprika",
            "Vitlök (marinerad)",
            "Oxfilé",
            "Bearnaisesås",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Forte",
        pris: "114:-",
        ingredienser: [
            "Köttfärs",
            "paprika",
            "rödlök",
            "soltorkade tomater",
            "Piri-piri",
        ],
        kategori: "pizzor",
    },
    {
        namn: "Acapulco",
        pris: "124:-",
        ingredienser: [
            "Oxfilé",
            "champinjoner",
            "rödlök",
            "marinerad vitlök",
            "färska tomater",
            "jalapeno",
        ],
        kategori: "pizzor",
    },
]
const salladOchKebaberArr = [
    {
        namn: "Insalata di pollo",
        pris: "119:-",
        ingredienser: ["Kycklingsallad"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di gamberi",
        pris: "119:-",
        ingredienser: ["Räksallad med handskalade räkor"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di kebab",
        pris: "119:-",
        ingredienser: ["Kebabsallad"],
        kategori: "salladOchKebaber",
    },
    {
        namn: "Insalata di formaggio",
        pris: "119:-",
        ingredienser: ["Sallad med blandade italienska ostar"],
        kategori: "salladOchKebaber",
    },
]

const lyxpizzorArr = [
    {
        namn: "Bufalotta e basillico",
        pris: "125:-",
        ingredienser: [
            "Buffelmozzarella",
            "färska basilika",
            "italiensk olivolja",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Formaggiara",
        pris: "114:-",
        ingredienser: ["Tre olika italienska ostar"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Tonno e capperi",
        pris: "109:-",
        ingredienser: ["Tonfisk", "rödlök", "Kaprisbär"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Barbabietole con formagio di capra",
        pris: "115:-",
        ingredienser: [
            "Torkade rotfrukter",
            "getost",
            "italiensk honung",
            "valnötter",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Verde natura",
        pris: "120:-",
        ingredienser: [
            "Karl-Johan svamp",
            "soltorkade tomater",
            "paprika",
            "konärtskocka",
            "oliver",
            "kaprisbär",
            "zucchini",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Prosciutto crudo e pesto",
        pris: "109:-",
        ingredienser: ["Lufttorkad prasciutto", "pesto"],
        kategori: "lyxpizzor",
    },
    {
        namn: "Parma noci",
        pris: "115:-",
        ingredienser: [
            "Lufttorkad prasciutto",
            "soltorkade tomater",
            "valnötter",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salsiccia con finocchio",
        pris: "115:-",
        ingredienser: [
            "Salsciccia smaksatt med fänkål",
            "Zucchini",
            "färska Champinjoner",
            "gorgonzolaost",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salame con tartufo",
        pris: "115:-",
        ingredienser: [
            "Salami från Modena",
            "inlagd paprika",
            "Provoloneost",
            "svart tryffelolja",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Salame piccante",
        pris: "115:-",
        ingredienser: [
            "Salami från Milano",
            "rödlök",
            "soltorkade tomater",
            "piri-piri",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Carne macinata",
        pris: "120:-",
        ingredienser: [
            "Köttfärs",
            "oxfilé",
            "gorgonzolaost",
            "Karl-Johan svamp",
            "bearnaisesås",
            "vitlök",
        ],
        kategori: "lyxpizzor",
    },
    {
        namn: "Frutti di mare",
        pris: "120:-",
        ingredienser: [
            "Tonfisk",
            "kokta musslor",
            "handskalade räkor",
            "bläckfisk",
            "färsk vitlök",
        ],
        kategori: "lyxpizzor",
    },
]

const nyheterArr = [
    {
        namn: "Mariaplan special",
        pris: "119:-",
        ingredienser: ["kebabkött", "skinka", "pommes", "valfri sås"],
        kategori: "nyheter",
    },
    {
        namn: "Florens Pizza",
        pris: "104:-",
        ingredienser: ["spenat", "soltorkade tomater", "vitlökssås"],
        kategori: "nyheter",
    },
    {
        namn: "Kebabrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "kebabkött", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kebabtallrik",
        pris: "94:-",
        ingredienser: ["pommes", "Kebabkött", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kycklingtallrik",
        pris: "94:-",
        ingredienser: ["Kyckling", "Pommes", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Kycklingrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "Kyckling", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Falafeltallrik",
        pris: "94:-",
        ingredienser: ["falafelbullar", "pommes", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Falafelrulle",
        pris: "94:-",
        ingredienser: ["tunnbröd", "falafelbullar", "grönsaker", "sås"],
        kategori: "nyheter",
    },
    {
        namn: "Pommestallrik",
        pris: "45:-",
        ingredienser: ["Krispiga och goda pommes frites"],
        kategori: "nyheter",
    },
    {
        namn: "Vegan kebabtallrik",
        pris: "109:-",
        ingredienser: ["vegankebab", "grönsaker", "vegansk sås"],
        kategori: "nyheter",
    },
    {
        namn: "Vegan kebabrulle",
        pris: "109:-",
        ingredienser: ["Vegankebab", "grönsaker", "vegansk sås"],
        kategori: "nyheter",
    },
]

const veganskaPizzorArr = [
    {
        namn: "Capricciosa Vegan",
        pris: "104:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "färska Champinjoner",
            "Vegan skinka",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Mexicana Vegan",
        pris: "114:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "rödlök",
            "Vegofärs",
            "Paprika",
            "Jalapeños",
            "ruccola",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Kebab Pizza",
        pris: "119:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "vegoKebab",
            "Isbergssallad",
            "färska tomater",
            "gurka",
            "rödlök",
            "peperoni",
            "vegansås",
        ],
        kategori: "veganskaPizzor",
    },
    {
        namn: "Flygande Jakob Vegan",
        pris: "119:-",
        ingredienser: [
            "Tomatsås",
            "vegan mozzarella",
            "banan",
            "ananas",
            "valnötter",
            "vegoKyckling",
            "curry",
            "vegansås",
        ],
        kategori: "veganskaPizzor",
    },
]

export {
    data,
    pizzorArr,
    lyxpizzorArr,
    nyheterArr,
    veganskaPizzorArr,
    salladOchKebaberArr,
}
